---
# tasks file for user
- name: User - Creating Desktop Directory
  file:
    path: /etc/skel/Desktop
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes

- name: User - Create User "{{ user_name }}"
  user:
    name: "{{ user_name }}"
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "{{ user_home }}"
    uid: "{{ user_uid }}"

- name: User - Install Rsync for userdir
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    autoremove: yes
    cache_valid_time: 3600
    install_recommends: no
  vars:
    packages:
    - rsync
