version: '3.1'
services:
  desktop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5901:5901"
      - "5911:5911"
    environment:
      - RESOLUTION=1920x1080
      - USE_SSL=false
    secrets:
      - VNC_RW_PASSWORD
      - VNC_RO_PASSWORD

secrets:
  VNC_RW_PASSWORD:
    file: ./secrets/VNC_RW_PASSWORD
  VNC_RO_PASSWORD:
    file: ./secrets/VNC_RO_PASSWORD
