version: '3.1'
services:
  desktop:
    image: mderasse/rdod:latest
    shm_size: 1g
    volumes:
      - ./home:/home/user
    ports:
      - "5901:5901"
      - "5911:5911"
    environment:
      - RESOLUTION=1920x1080
      - USE_SSL=false
    secrets:
      - VNC_RW_PASSWORD
      - VNC_RO_PASSWORD

secrets:
  VNC_RW_PASSWORD:
    file: ./secrets/VNC_RW_PASSWORD
  VNC_RO_PASSWORD:
    file: ./secrets/VNC_RO_PASSWORD
