---
# tasks file for python
- name: Python - Install Python and dependencies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    autoremove: yes
    cache_valid_time: 3600
    install_recommends: no
  vars:
    packages:
    - python2.7
    - python3.7
    - python3-pip
    - python-pip
