---
- name: Vscode - Download and Install Deb package
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
    state: present
    update_cache: yes
    autoremove: yes
    cache_valid_time: 3600
    install_recommends: no

- name: Vscode - Add Shortcut on Desktop
  copy:
    src: /usr/share/applications/code.desktop
    dest: /etc/skel/Desktop/code.desktop
    owner: user
    group: user
    mode: 0755
